apiVersion: v1
clusters:
  - cluster:
      server: __OPENSHIFT_API_URL__
      insecure-skip-tls-verify: true
    name: cluster
contexts:
  - context:
      cluster: cluster
      namespace: default
      user: admin/cluster
    name: default/cluster/admin
current-context: default/cluster/admin
kind: Config
preferences: {}
users:
  - name: admin/cluster
    user:
      token: __OPENSHIFT_API_TOKEN__
